apiVersion: v1
kind: ConfigMap
metadata:
  name: high-performance-api-config
data:
  SERVER_PORT: "8080"
  APP_URL: "http://localhost"

  POSTGRES_HOST: "172.19.0.1"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "order_processing"

  REDIS_HOST: "172.19.0.1"
  REDIS_PORT: "6379"

  SECURITY_ACCOUNT_LOCKOUT_MAX_FAILED_ATTEMPTS: "5"
  SECURITY_ACCOUNT_LOCKOUT_LOCK_DURATION_SECONDS: "900"

  RATE_LIMIT_CAPACITY: "10"
  RATE_LIMIT_REFILL_TOKENS: "10"
  RATE_LIMIT_REFILL_DURATION_SECONDS: "60"

  JWT_EXPIRATION: "3600000"
  JWT_REFRESH_EXPIRATION: "604800000"
