apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "high-performance-api.fullname" . }}-config
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  APP_URL: {{ .Values.config.appUrl | quote }}

  POSTGRES_HOST: {{ .Values.config.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.config.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}

  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}

  SECURITY_ACCOUNT_LOCKOUT_MAX_FAILED_ATTEMPTS: {{ .Values.config.securityAccountLockoutMaxFailedAttempts | quote }}
  SECURITY_ACCOUNT_LOCKOUT_LOCK_DURATION_SECONDS: {{ .Values.config.securityAccountLockoutLockDurationSeconds | quote }}

  RATE_LIMIT_CAPACITY: {{ .Values.config.rateLimitCapacity | quote }}
  RATE_LIMIT_REFILL_TOKENS: {{ .Values.config.rateLimitRefillTokens | quote }}
  RATE_LIMIT_REFILL_DURATION_SECONDS: {{ .Values.config.rateLimitRefillDurationSeconds | quote }}

  JWT_EXPIRATION: {{ .Values.config.jwtExpiration | quote }}
  JWT_REFRESH_EXPIRATION: {{ .Values.config.jwtRefreshExpiration | quote }}
